apiVersion: v2
name: commerce
description: Umbrella chart for the order/stock practice app.
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"

dependencies:
  - name: order-service
    version: 0.1.0
    repository: "file://./charts/order-service"
  - name: stock-service
    version: 0.1.0
    repository: "file://./charts/stock-service"
  - name: pulsar
    version: 0.1.0
    repository: "file://./charts/pulsar"
    condition: pulsar.enabled
  - name: postgresql
    version: "16.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "21.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
