{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pulsar.fullname" . }}-data
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end -}}
