apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsar.fullname" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pulsar.selectorLabels" . | nindent 4 }}
  ports:
    - name: broker
      port: {{ .Values.service.brokerPort }}
      targetPort: broker
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
